#
# This file contains configuration flags to customize your site
#

# Site details (displayed in the header)
author: Dojo Entertainment
name: Drinking Dojo Blog
title: Drinking Dojo Blog
description: Your hub for party games!
keywords: "drinking games, entertainment, party games, hygge"
logo: images/dojoIcon.svg

# Company details
company:
  analytics:
    google_id: G-1PQ65P1MSM
    google_ads: true
  cta:
    text: "Play drinking games online"
    url: "https://drinkingdojo.com/"
  socials:
    youtube: "@DrinkingDojo"
    instagram: 
    facebook: DrinkingDojo
    tiktok: 
    x: 
    linkedin: company/drinking-dojo/
    pinterest: 
    telegram: 
    discord: 
    github: 
    email: contact@drinkingdojo.com
    phone: 
  icon_size: "24"
  colors:
    main:
      background: "#18181f"
      foreground: "#fff"
    body:
      background: "#18181f"
      foreground: "#fff"
    accent: "#ff9800"
  fonts:
    google:
      - "Bungee"
    heading: "'Bungee', 'Helvetica Neue'"
    body: "'Helvetica Neue'"

# Navigation items
navigation:
  header:
    - title: "Play Now"
      url: "https://drinkingdojo.com/"
  footer:
    - title: "Terms and Conditions"
      url: "/terms-and-conditions"
    - title: "Privacy Policy"
      url: "/privacy-policy"
    - title: "Cookie Policy"
      url: "/cookie-policy"

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://127.0.0.1:4000/

# Paginate after X amount of posts
paginate: 10

#
# NOTHING TO CHANGE BEYOND THIS POINT
#

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
# ONLY NECESSARY ON SUB-PAGE / GITHUB-BASED HOSTING
baseurl: 

# Theme used as a base
theme: jekyll-swiss

# Slug of paginated page
paginate_path: "/page-:num/"

# Permalink slug (DO NOT TOUCH)
permalink: /:title/

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Disable Github Metadata plugin
github: [metadata]

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap
  - jekyll-feed # Create an Atom RSS feed
  - jekyll-paginate # Support pagination of posts

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - __init/
  - init_mac.command
  - init_windows.bat